# Generated by Django 4.1.7 on 2023-03-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO store_collection (title)
                VALUES ("collection1")
                          """,
                          """
                DELETE FROM store_collection
                WHERE title = "Collection 1"
                          """)
    ]
